---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post-with-image
- type: heading
  label: Languages
- type: directory
  path: content/chinese
  label: Chinese
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content/french
  label: French
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content/german
  label: German
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content/greek
  label: Greek
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content/italian
  label: Italian
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content/japanese
  label: Japanese
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content./korean
  label: Korean
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content/portuguese
  label: Portuguese
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content/spanish
  label: Spanish
  create: documents
  match: "**/*"
  templates:
  - post-with-image
- type: directory
  path: content/russian
  label: Russian
  create: documents
  match: "**/*"
  templates:
  - post-with-image
upload_dir: content/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public --config config.toml,.forestry/config-overrides.toml
version: 0.54.0
