---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/cx
  label: Cx
  create: all
  match: "**/*"
- type: directory
  path: content/ask-the-developers
  label: Ask the developers
  create: all
  match: "**/*"
- type: directory
  path: content/bbs
  label: Bbs
  create: all
  match: "**/*"
- type: directory
  path: content/infographics
  label: Infographics
  create: all
  match: "**/*"
- type: directory
  path: content/development-updates
  label: Development updates
  create: all
  match: "**/*"
- type: directory
  path: content/statement
  label: Statement
  create: all
  match: "**/*"
- type: directory
  path: content/skywire
  label: Skywire
  create: all
  match: "**/*"
- type: directory
  path: content/img
  label: Img
  create: all
  match: "**/*"
- type: directory
  path: content/guest-post
  label: Guest post
  create: all
  match: "**/*"
- type: directory
  path: content/overview
  label: Overview
  create: all
  match: "**/*"
- type: directory
  path: content/drafts
  label: Drafts
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
